[package]
authors = ["Matt Hauck <matt.hauck@tanium.com>"]
name = "octobot"
version = "0.1.0"

[dependencies]
bodyparser = "0.4.1"
env_logger = "0.3.5"
iron = "0.4.0"
logger = "0.2.0"
persistent = "0.2.1"
ring = "0.6.1"
router = "0.4.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.22"
toml = "0.2.1"
