[package]
authors = ["Matt Hauck <matt.hauck@tanium.com>"]
name = "octobot"
version = "0.1.0"

[[bin]]
doc = false
name = "octobot"
path = "src/main.rs"

[[bin]]
doc = false
name = "octobot-ask-pass"
path = "src/ask-pass.rs"

[[bin]]
doc = false
name = "octobot-passwd"
path = "src/octobot-passwd.rs"

[[bin]]
doc = false
name = "ldap-check"
path = "src/ldap-check.rs"

[[bin]]
doc = false
name = "migrate-db"
path = "src/migrate-db.rs"

[dependencies]
base64 = "0.9.2"
env_logger = "0.5.10"
error-chain = "0.12.0"
futures = "0.1.23"
http = "0.1.7"
hyper = "0.12.6"
hyper-rustls = "0.13.0"
ldap3 = "0.6.0"
log = "0.4.3"
maplit = "1.0.1"
regex = "1.0.1"
ring = "0.13.2"
rpassword = "2.0.0"
rusqlite = "0.13.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.24"
rustls = "0.12.0"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.22"
thread-id = "3.3.0"
time = "0.1.40"
tokio = "0.1.7"
tokio-core = "0.1.17"
tokio-rustls = "0.6.0"
toml = "0.4.6"
unidiff = "0.2.1"
url = "1.7.1"

[dependencies.jsonwebtoken]
git = "https://github.com/matthauck/jsonwebtoken"
rev = "94917bfe2ccf33853a1d57094138f9e9d42c5a86"

[dev-dependencies]
tempdir = "0.3.7"

[lib]
doc = false
name = "octobot"
path = "src/lib.rs"
