[package]
authors = ["Matt Hauck <matt.hauck@tanium.com>"]
name = "octobot"
version = "0.1.0"

[[bin]]
name = "octobot"
path = "src/main.rs"

[[bin]]
name = "octobot-ask-pass"
path = "src/ask-pass.rs"

[[bin]]
name = "octobot-passwd"
path = "src/octobot-passwd.rs"

[dependencies]
base64 = "0.7.0"
bodyparser = "^0.7"
env_logger = "^0.4"
futures = "0.1.16"
hyper = "^0.11"
hyper-tls = "0.1.2"
iron = "0.5.1"
log = "0.3.7"
logger = "^0.3"
maplit = "0.1.5"
regex = "^0.2"
ring = "^0.12"
router = "^0.5"
rpassword = "^1.0"
rust-crypto = "0.2.36"
rustc-serialize = "^0.3"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
thread-id = "^3.0"
threadpool = "^1.0"
time = "^0.1"
tokio-core = "0.1.10"
toml = "^0.4"
unidiff = "0.2.0"
url = "^1.5"

[dev-dependencies]
tempdir = "0.3.5"

[lib]
name = "octobot"
path = "src/lib.rs"
